insert into ADDRESSENTRY (ID, NAME) values (1, 'Petar Petrovic');
insert into ADDRESSENTRY (ID, NAME) values (2, 'Jovan Jovic');
insert into ADDRESSENTRY (ID, NAME) values (3, 'Zika Zivkovic');
insert into ADDRESSENTRY (ID, NAME) values (4, 'Ana Bozic');
insert into ADDRESSENTRY (ID, NAME) values (5, 'Milica Ilic');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1, 'NUMBER', '021/219417');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1, 'NUMBER', '021/219417');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1,'NUMBER','069/8294145');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (2,'NUMBER','021/784452');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (3,'NUMBER','021/121365');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1,'NUMBER','065/2819417');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (3,'NUMBER','061/2361458');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (4,'NUMBER','021/011015');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (4,'NUMBER','063/4557412');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'NUMBER','021/008892');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'NUMBER','064/8852146');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (3,'NUMBER','066/3663304');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (2,'NUMBER','069/3725081');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'NUMBER','063/5325412');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1,'ADDRESS','Gogoljeva 3');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1,'ADDRESS','Bulevar oslobodjenja 72');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (2,'ADDRESS','Bulevar cara Lazara 30');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (3,'ADDRESS','Strazilovska 13');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (4,'ADDRESS','Heroja Pinkija 9');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (4,'ADDRESS','Stevana Mokranjca 9');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'ADDRESS','Narodnog fronta 21');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1,'EMAIL','ppetrovic@gmail.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1,'EMAIL','perapetrovic@yahoo.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (2,'EMAIL','joca@gmail.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (2,'EMAIL','jovanjj@hotmail.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (3,'EMAIL','zikica@yahoo.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (4,'EMAIL','anabozic90@gmail.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'EMAIL','micailic@live.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'EMAIL','milicm@gmail.com');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'NOTE','KBDkajbfja');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (5,'NOTE','asfcma;lsfma;');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (4,'NOTE','aslkfnalkwf');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (4,'NOTE','afvafnajwn');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (3,'NOTE','afclanfh');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (3,'NOTE','asvchawofjwsnc');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (2,'NOTE','awfcjawfbnjencf');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (2,'NOTE','cflwsnfciwjsc');
insert into DETAIL (ENTRYID, DETAILTYPE, DETAILVALUE) values (1,'NOTE','lcnvalskncfpao');